---
title: "RoundReturns"
output: html_document
---

### Returns by Round
The table below provides insights into which rounds are historically the best and worst for individual GMs as compared to the entire league. The returns column is the average fantasy points scored above or below pre-season projections, respective to each round for the selected GM. For example, Ghost's return in the 4th round is 32.75, indicating that on average his 4th round picks have exceeded preseason projections by 32.75 fantasy points. The league returns column shows the same calculation for all GMs, providing insights into which GMs have done better or worse than the market. It should be noted, the statistic is inherently negatively skewed. Consider the significant negative impact busts or injuried players have on the statistic in comparison to a player whom has a good year, lets say meets expectations. The former will have a large negative return, while the latter will have a zero return. Thus, GMs should measure their performance relative to the league and not on an absolute basis. Users can change the parameters using the input boxes and sliders above.    