#Define UI script for application
shinyUI(fluidPage(
      navbarPage("The Inebriation Confederation",
                  theme = mycss,
                 tabPanel("Home", icon = icon('home'),
                          fluidPage(
                            tags$head(includeScript("www/twittermike.js")),            
                            fluidRow(column(width = 7, img(src = 'home_logo.jpg',
                            width = 200, height = 100, style = "float:left; padding-right:10px"),
                            div(br(),
                            "The Home of The Golden Delakas", br(),
                            " - Commisioner Gordan"),
                            br(),br(), br(), br(),
                            includeMarkdown("html/overview.Rmd")
                            ),
                            column(width = 5,
                                   a(class="twitter-timeline","data-height" = "800", href="https://twitter.com/POCKETsurACES/lists/fantasy-news",
                                     src="//platform.twitter.com/widgets.js"))))),
                 
                 
                 navbarMenu("Analytics", icon = icon('bar-chart'),
                      tabPanel("Rankings", icon = icon('tasks'),
                               fluidPage(fluidRow(column(width= 4,
                                          includeMarkdown("html/rankings.Rmd")),
                                         column(width = 8, 
                                                  DT::dataTableOutput('TeamRankings'))))),
                      
                      
                      tabPanel("Game Logs", icon = icon('google'),
                               fluidPage(fluidRow(column(width = 3,
                                                      selectInput('GM',"Select a Team:",team_list)),
                                                  column(width = 3,
                                                         sliderInput('period',"Choose Time Period:",min = 2012, max = 2016,
                                                                     value = c(2012,2016), sep =""))),
                                         fluidRow(DT::dataTableOutput('gamelogs')))),
                      
                          
                      tabPanel("Playoff Stats", icon = icon('tasks'),
                               DT::dataTableOutput('PlayoffData')),
                      
                      
                      tabPanel("Trend Analysis", icon = icon('line-chart'),
                            fluidPage(fluidRow(column(width = 12,includeMarkdown("html/trend.Rmd"))),
                                      fluidRow(column(width = 3,selectInput('team', "Select a Team:", team_list)),
                                               column(width = 3,sliderInput('year', "Choose Your Timeframe:", min = 2012, max = 2016,value = c(2012,2016), sep =""))),
                                      br(),
                                      fluidRow(column(width = 5,
                                                      DT::dataTableOutput('trend')),
                                              column(width = 6, offset = 1,
                                                      plotlyOutput('barchart')))),
                                      br(), br(), br())),
                 
                 
                  tabPanel("League Rules",
                            tags$iframe(style = "height:1000px; width:100%; scrolling=yes",
                                          src = "Rule_Updated.pdf")),
                 
                 
                 tabPanel("Meet the Inebo",
                          fluidPage(div("Player Profile",
                                      br(), br(), br()),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/milk_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "milk.jpg",width = 300, height = 300))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/surace_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "surace.jpg",width = 300, height = 300))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/ghost_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "ghost.jpg",width = 300, height = 300))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/poppy_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "poppy.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/commish_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "commish.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/white_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "white.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/gietz_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "gietz.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/ben_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "ben.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/greek_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "greek.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/richard_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "richard.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/dunn_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "dunn.jpg",width = 300, height = 300))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/jerry_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "jerry.jpg",width = 300, height = 300))),
                                    br(), br(), br())),
                 
                 navbarMenu("Draft Corner", icon = icon('bar-chart'),
                  tabPanel("Historical Results",
                           fluidPage(fluidRow(column(width = 3,
                                                    selectInput('yr',"Select a Year:",c(2016,2015,2014,2013,2012)))),
                                    fluidRow(column(width = 12,
                                                    DT::dataTableOutput('draftgrid'))))),
                           
                  tabPanel("Draft Tendencies",
                          fluidPage(fluidRow(column(width = 12,
                                                    includeMarkdown('html/DraftTrends.Rmd'))),
                                    fluidRow(column(width = 3,selectInput('dtTeam',"Choose General Manager(s):",team_list)),
                                             column(width = 3,selectInput('dtPOS',"Select a Position (Chart Only):",c('QB','WR','RB','TE')))),
                                    br(),br(),
                                    fluidRow(column(width = 5,
                                                    DT::dataTableOutput('Draft')),
                                             column(width = 7,
                                                    plotlyOutput('TrendRound'))),
                                    br())),
                  tabPanel("Player Returns",
                             fluidPage(fluidRow(column(width = 12, includeMarkdown("html/BestDraft.Rmd"))),
                                       fluidRow(column(width = 12, DT::dataTableOutput('TopDraft'))),
                                       fluidRow(column(width = 12,includeMarkdown("html/SeasonReturns.Rmd"))),
                                       fluidRow(column(width = 4,selectInput('SeasonTeam',"Select a General Manager:",team_list)),
                                                column(width = 3,selectInput('SeasonYear',"Select a Season:",c(2016,2015,2014,2013,2012)))),
                                       fluidRow(column(width = 12,DT::dataTableOutput('draftresults'))),
                                       fluidRow(column(width = 12,includeMarkdown('html/RoundReturns.Rmd'))),
                                       fluidRow(column(width = 4,selectInput('RoundTeam',"Select a General Manager:",team_list)),
                                                column(width = 4,sliderInput('RoundYear', "Choose Which Season(s):", min = 2012, max = 2016, value = c(2012,2016), sep =""))),
                                       fluidRow(column(width = 12,DT::dataTableOutput('RdPts'))),
                                       fluidRow(column(width = 12,includeMarkdown('html/PositionReturns.Rmd'))),
                                       fluidRow(column(width = 4, selectInput('PositionTeam',"Select a General Manager:",team_list)),
                                                column(width = 4, sliderInput('PositionYear',"Choose Which Season(s):",min=2012,max=2016,value = c(2012,2016),sep=""))),
                                       fluidRow(column(width = 12, DT::dataTableOutput('PosPts'))),
                                       br(),br()))),
                 tabPanel("Trade Evaulator",
                          includeMarkdown('html/Trades.Rmd'))

)))



